default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, admin.css]

  #javascripts:    []
  javascripts:
    - jquery.min.js #- http://ajax.googleapis.com/ajax/libs/jquery/1.2.6/jquery.min.js
    - interface/interface.js
    - inestedsortable-1.0.1.pack.js

  has_layout:     on
  layout:         layout
