#!/bin/bash
echo " _____________________________________________ "
echo "|                                             |"
echo "|           timenote update v0.1              |"
echo "|      .: update your timenote app :.         |"
echo "|_____________________________________________|"

##
# GENERAL
##
WRKDIR="/var/www/timenote";

##
# GOTO DIRECTORY
##
echo "- moving in your timenote directory"
cd $WRKDIR
pwd

echo 

##
# SUBVERSION UPDATE
##
retour=X
while [ "$retour" = "X" ]; do
echo -n "- run svn up ? [y/n] " 
read respone
case "$respone" in
y*| Y* | o* | O* ) 
echo "... updating your timenote local copy with the repository"
svn up
retour=0
;;
[nN]* )
echo "... skipping the update of working copy"
retour=1
;;
"?"* )
echo "launch svn up in here"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retour

##
# TESTING DIRECTORY CHMODAGE
## 
echo "- testing cache and log dirs chmod"
if test -w $WRKDIR/cache
then 
  echo "... cache already ok"
else 
  sudo chmod 777 -R $WRKDIR/cache
  echo "... cache successfuly chmoded"
fi

if test -w $WRKDIR/log
then
  echo "... log dir already ok"
else
  sudo chmod 777 -R $WRKDIR/cache
  echo "... log dir successfuly chmoded"
fi

echo

##
# PROPEL BUILD ALL
##
retour=X
while [ "$retour" = "X" ]; do
echo -n "- run propel build all ? [y/n] " 
read respone
case "$respone" in
y*| Y* | o* | O* )
echo "... running propel build all"
php symfony propel:build-all
retour=0
;;
[nN]* )
echo "... skipping propel build all"
retour=1
;;
"?"* )
echo "launch propel build all here"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retour

##
# PROPEL LOAD DATA
##
retour=X
while [ "$retour" = "X" ]; do
echo -n "- run propel load data ? [y/n] " 
read respone
case "$respone" in
y*| Y* | o* | O* ) 
echo "... running propel load data"
php symfony propel:data-load
retour=0
;;
[nN]* )
echo "... skipping propel load data"
retour=1
;;
"?"* )
echo "launch propel load data here"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retour

echo

##
# SYMFONY CLEAR CACHE
##
retour=X
while [ "$retour" = "X" ]; do
echo -n "- run symfony cc ? [y/n] "
read respone
case "$respone" in
y*| Y* | o* | O* )
echo "... running symfony clear:cache task"
php symfony cc
retour=0
;;
[nN]* )
echo "... skipping clearing of cache"
retour=1
;;
"?"* )
echo "clear the cache of the timenote project"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retour


##
# ENDING
##
echo "- that's it, go to"
echo "http://localhost/timenote"

exit 0

