#!/bin/bash
echo " _____________________________________________ "
echo "|                                             |"
echo "|           timenote update v0.1              |"
echo "|      .: update your timenote app :.         |"
echo "|_____________________________________________|"

##
# GENERAL
##
WRKDIR="/var/www/timenote";

##
# GOTO DIRECTORY
##
echo "- moving in your timenote directory"
cd $WRKDIR
pwd

echo 

##
# SUBVERSION UPDATE
##
retoura=X
while [ "$retoura" = "X" ]; do
echo -n "- run svn up ? [y/n] " 
read response
case "$response" in
y*| Y* | o* | O* ) 
echo "... updating your timenote local copy with the repository"
svn up
retoura=0
;;
[nN]* )
echo "... skipping the update of working copy"
retoura=1
;;
"?"* )
echo "launch svn up in here"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retoura

##
# TESTING DIRECTORY CHMODAGE
##  
# TODO test if cache dir is writable by apache www-data user!
echo "- testing cache and log dirs chmod"
if test -w $WRKDIR/cache
then 
  echo "... cache already ok"
else 
  sudo chmod 777 -R $WRKDIR/cache
  echo "... cache successfuly chmoded"
fi

echo "... touching file /log/frontend_dev.log"
touch $WRKDIR/log/frontend_dev.log

# TODO test if log dir is writable by apache www-data user!
#if test -w $WRKDIR/log
#then
#  echo "... log dir already ok"
#else
  echo "... chmoding log dir"
  sudo chmod 777 -R $WRKDIR/log
  echo "... log dir successfuly chmoded"
#fi

echo 

##
# CLEANING LIBs
##
retourb=X
while [ "$retourb" = "X" ]; do
echo -n "- clean all libs ? [y/n] " 
read response
case "$response" in
y*| Y* | o* | O* ) 
echo "... cleaning lib/filter/base/*"
rm -f $WRKDIR/lib/filter/base/*.php
echo "... cleaning lib/form/base/*"
rm -f $WRKDIR/lib/form/base/*.php
echo "... cleaning lib/filter/base/*"
rm -f $WRKDIR/lib/model/map/*.php
echo "... cleaning lib/filter/base/*"
rm -f $WRKDIR/lib/model/om/*.php
echo "... libs successfully cleaned"
echo "... running propel build all"
php symfony propel:build-all
retourb=0
;;
[nN]* )
echo "... skipping the libs cleaning"
retourb=1
;;
"?"* )
echo "clean filter, form, model base libs"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retourb

echo

##
# PROPEL BUILD ALL LOAD
# OR PROPEL BUILD ALL AND PROPEL LOAD DATA
##
retourc=X
while [ "$retourc" = "X" ]; do
echo -n "- run propel build all load ? [y/n] " 
read response
case "$response" in
y*| Y* | o* | O* )
echo "... running propel build all load"
php symfony propel:build-all-load
retourc=0
;;
[nN]* )
	echo "... skipping propel build all load"
	### start propel buil all load skip
	echo 
	##
	# PROPEL BUILD ALL
	##
	retourd=X
	while [ "$retourd" = "X" ]; do
	echo -n "- run propel build all ? [y/n] " 
	read response
	case "$response" in
	y*| Y* | o* | O* )
	echo "... running propel build all"
	php symfony propel:build-all
	retourd=0
	;;
	[nN]* )
	echo "... skipping propel build all"
	retourd=1
	;;
	"?"* )
	echo "launch propel build all here"
	;;
	* )
	echo "Error : press [y]es ou [n]o."
	;;
	esac
	echo 
	done
	##exit $retourc

	##
	# PROPEL LOAD DATA
	##
	retoure=X
	while [ "$retoure" = "X" ]; do
	echo -n "- run propel load data ? [y/n] " 
	read response
	case "$response" in
	y*| Y* | o* | O* ) 
	echo "... running propel load data"
	php symfony propel:data-load
	retoure=0
	;;
	[nN]* )
	echo "... skipping propel load data"
	retoure=1
	;;
	"?"* )
	echo "launch propel load data here"
	;;
	* )
	echo "Error : press [y]es ou [n]o."
	;;
	esac
	echo 
	done
	##exit $retoure
	### end propel buil all load skip
	retourc=1
;;
"?"* )
echo "launch propel build all load here"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retourc

##
# SYMFONY CLEAR CACHE
##
retourf=X
while [ "$retourf" = "X" ]; do
echo -n "- run symfony cc ? [y/n] "
read response
case "$response" in
y*| Y* | o* | O* )
echo "... running symfony clear:cache task"
php symfony cc
retourf=0
;;
[nN]* )
echo "... skipping clearing of cache"
retourf=1
;;
"?"* )
echo "clear the cache of the timenote project"
;;
* )
echo "Error : press [y]es ou [n]o."
;;
esac
echo 
done
##exit $retourf


##
# ENDING
##
echo "- end of script, go to http://timenote"
echo " ____________________________________________________ "
echo "|                                                    |"
echo "| site:     http://timenote                          |"
echo "| gproject: http://timenote.googlecode.com/          |"
echo "| ggroup:   http://groups.google.com/group/timenote  |"
echo "| symfony:  http://www.symfony-project.org/doc/1_2/  |"
echo "|____________________________________________________|"
exit 0

