# sf_guard rules
sf_guard_signin:
  url:   /signin
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /signout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /gimmemypassword
  param: { module: sfGuardAuth, action: password }


# default rules
homepage:
  url:   /
  param: { module: capture, action: main }
  #param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

timenote_hour:
  class: sfPropelRouteCollection
  options:
    model:                TimenoteHour
    module:               entry
    prefix_path:          entry
    column:               id
    with_wildcard_routes: true

timenote_hour_category:
  class: sfPropelRouteCollection
  options:
    model:                TimenoteHourCategory
    module:               type
    prefix_path:          type
    column:               id
    with_wildcard_routes: true

timenote_project:
  class: sfPropelRouteCollection
  options:
    model:                TimenoteProject
    module:               project
    prefix_path:          project
    column:               id
    with_wildcard_routes: true


#timenote_dayoff:
#  class: sfPropelRouteCollection
#  options:
#    model:                TimenoteDayoff
#    module:               dayoff
#    prefix_path:          dayoff
#    column:               id
#    with_wildcard_routes: true