default: #TODO: precise this
  javascripts:
    [jquery.min.js, jquery.maskedinput-1.2.2.min.js, jquery-ui/js/jquery-ui-1.7.2.custom.min.js]
  stylesheets: [main.css, jquery-ui/ui-lightness/jquery-ui-1.7.2.custom.css]