dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'mysql:dbname=timenote;host=localhost'
      username: timenote
      password: t1men@te
      encoding: utf8
      persistent: true
      pooling: true