propel:
  # Projects table
  timenote_project:
    _attributes: {treeMode: NestedSet}
    id: 
    title:       { type: varchar(255), required: true, index: true}
    description: longvarchar
    slug:        { type: varchar(60), index: true}
    lft:         { type: integer, required: true, nestedSetLeftKey: true} # required for nested set!
    rgt:         { type: integer, required: true, nestedSetRightKey: true} # required for nested set!
    is_counted:  { type: boolean, required: true} # counted or uncounted hours in project
    created_at:
    updated_at:

  timenote_project_behaviors:
    id:
    project_id:  { type: integer, foreignTable: timenote_project, foreignReference: id, required: true }
    title:       { type: varchar(255), required: true, index: true}
    description: longvarchar

  timenote_hour_category:
    id:
    title:       { type: varchar(255), required: true, index: true}
    description: longvarchar
    slug:        { type: varchar(60), index: true}
    created_at:
    updated_at:

  # Entries table
  timenote_hour:
    id:
    project_id:  { type: integer, foreignTable: timenote_project, foreignReference: id, required: true }
    cat_id:      { type: integer, foreignTable: timenote_hour_category, foreignReference: id, required: true }
    user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    #timenote_project_id: { type: integer, required: true, primaryKey: true, foreignTable: timenote_project, foreignReference: id }
    #timenote_type_id: { type: integer, required: true, primaryKey: true, foreignTable: timenote_type, foreignReference: id }
    start_dt:    TIMESTAMP
    end_dt:      TIMESTAMP
    comment:     { type: varchar(255), required: false, index: false}

  sf_guard_user_profile:
    _attributes: { phpName: sfGuardUserProfile }
    id:
    user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    remember:    boolean
    first_name:  varchar(120)
    last_name:   varchar(120)
    email:       varchar(255)
    birthday:    date
    sciper:      varchar(10)
    created_by:  { type: integer, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    version:     integer
    percent:     float # to tell the % of activity of the user


  user_worktime:
    id:
    user_id:     { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    serie_start: TIMESTAMP
    timeline_generator_id:
    timeline_generator_workdays:   { type: longvarchar }  # use implode to store here, and explode to recover the array
    timeline_generator_offdays: { type: longvarchar }
    timeline_generator_hours_start: { type: longvarchar }
    timeline_generator_hours_stop: { type: longvarchar }


  timeline_generator:
    id:
    date_start: TIMESTAMP
    workdays:  longvarchar
    off_days:  longvarchar
    hours_start: longvarchar
    hours_stop: longvarchar
